name: MC-Backrooms
version: '${project.version}'
main: com.backrooms.BackroomsPlugin
api-version: '1.21'
depend: [WorldEdit]
description: A procedural Backrooms world generator tile system.
author: Brock